apiVersion: v1
kind: Pod
metadata:
  name: viewer-pod
spec:
  nodeName: k8s-altra-01.sdsc.optiputer.net
  tolerations:
  - key: nautilus.io/csu-tide
    operator: Exists
    effect: NoSchedule
  - key: nautilus.io/arm64
    operator: Exists
    effect: NoSchedule
  restartPolicy: Never
  containers:
  - name: viewer
    image: gitlab-registry.nrp-nautilus.io/sappleby/r-containers/rbirds-multiarch:latest
    command: ["bash", "-c", "ls /data; sleep 3600"]
    resources:
      limits:        
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: appleby-volume
