apiVersion: batch/v1
kind: Job
metadata:
  name: maps-2-job
spec:
  completions: 3940
  parallelism: 120
  completionMode: Indexed
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
          - weight: 50
            preference:
              matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - "true"
      containers:
      - name: maps-models
        image: gitlab-registry.nrp-nautilus.io/sappleby/r-containers/rbirds-multiarch:latest
        workingDir: /data/MAPS
        command: ["Rscript"]
        args: ["maps-run.R"]
        resources:
          limits:
            cpu: 2
            memory: 1200Mi
          requests:
            cpu: 2
            memory: 1000Mi
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Never
      tolerations:
      - key: nautilus.io/csu-tide
        operator: Exists
        effect: NoSchedule
      - key: nautilus.io/arm64
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: appleby-volume
