apiVersion: v1
kind: Pod
metadata:
  name: data-combine-pod-maps
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: nautilus.io/csu-tide
              operator: Exists
  tolerations:
  - effect: NoSchedule
    key: nautilus.io/csu-tide
    operator: Exists
  restartPolicy: Never
  initContainers:
  - name: get-rscript
    image: bitnami/git:latest
    command: ["/bin/bash"]
    args: ["-c", "curl -o /data/MAPS/combine-data-maps.R \"https://raw.githubusercontent.com/slejennings/MAPS-Bootstrap/refs/heads/main/Scripts/combine-data-maps.R\""]
    volumeMounts:
    - mountPath: /data
      name: data
  containers:
  - name: run-datacombine
    image: gitlab-registry.nrp-nautilus.io/sappleby/r-containers/rbirds-multiarch:latest
    workingDir: /data/MAPS
    command: ["Rscript", "combine-data-maps.R"]
    resources:
      limits:        
        cpu: 10
        memory: 10Gi
      requests:
        cpu: 8
        memory: 8Gi
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: appleby-volume
