apiVersion: v1
kind: Pod
metadata:
  name: data-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: nautilus.io/csu-tide
              operator: Exists
  tolerations:
  - effect: NoSchedule
    key: nautilus.io/csu-tide
    operator: Exists
  restartPolicy: Never
  initContainers:
  - name: get-files
    image: bitnami/git:latest
    command: ["/bin/bash", "mkdir -p /data/MAPS"]
    command: ["/bin/bash", "-c", "curl -o /data/MAPS/get-data-birds.sh \"https://gitlab.nrp-nautilus.io/sappleby/k8stest/-/raw/main/hello_job_R/get-data-birds.sh\""]
    command: ["/bin/bash", "/data/MAPS/get-data-birds.sh"]
    volumeMounts:
    - mountPath: /data
      name: data
  containers:
  - name: data
    image: gitlab-registry.nrp-nautilus.io/sappleby/r-containers/rbirds:latest
    command: ["Rscript", "/data/MAPS/bird_data_prep.R"]
    resources:
      limits:        
        cpu: 16
        memory: 32Gi
      requests:
        cpu: 4
        memory: 16Gi
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: appleby-volume
