apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-job-example-birds
spec:
  completions: 20
  parallelism: 5
  completionMode: Indexed
  template:
    spec:
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
      containers:
      - name: birds
        image: gitlab-registry.nrp-nautilus.io/sappleby/r-containers/rbirds:latest
        command: ["/bin/bash", "/data/MAPS/bird-run.sh"]
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Never
      tolerations:
      - key: nautilus.io/csu-tide
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: appleby-volume
