apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-job-example
spec:
  completions: 20
  parallelism: 10
  completionMode: Indexed
  template:
    spec:
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/csu-tide
                operator: Exists
      containers:
      - name: pre-processor
        image: python:3
        command: ["/bin/bash", "/data/test/wiki-text.sh"]
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: data
      restartPolicy: Never
      tolerations:
      - key: nautilus.io/csu-tide
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: appleby-volume
