apiVersion: v1
kind: Pod
metadata:
  name: viewer-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: nautilus.io/csu-tide
              operator: Exists
  tolerations:
  - effect: NoSchedule
    key: nautilus.io/csu-tide
    operator: Exists
  restartPolicy: Never
  containers:
  - name: viewer
    image: gitlab-registry.nrp-nautilus.io/sappleby/r-containers/rbirds-multiarch:latest
    command: ["bash", "-c", "ls /data; sleep 3600"]
    resources:
      limits:        
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: appleby-volume
